// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH8nE8TaB2c2FXirn-u8NRgiPr9YLaKVE',
    appId: '1:780077026565:web:577c80d46ebde384f53b6c',
    messagingSenderId: '780077026565',
    projectId: 'appfinanzas-3a1ca',
    authDomain: 'appfinanzas-3a1ca.firebaseapp.com',
    storageBucket: 'appfinanzas-3a1ca.firebasestorage.app',
    measurementId: 'G-Z8N5Z2LEXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoUcQrY0AwOuWPE-1YxTyk72eHoSlHgd4',
    appId: '1:780077026565:android:599f1840e79fb667f53b6c',
    messagingSenderId: '780077026565',
    projectId: 'appfinanzas-3a1ca',
    storageBucket: 'appfinanzas-3a1ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCdED9GvM7dpaSpIqGSTI3RdzZYSI48h0',
    appId: '1:780077026565:ios:259260e698d0b742f53b6c',
    messagingSenderId: '780077026565',
    projectId: 'appfinanzas-3a1ca',
    storageBucket: 'appfinanzas-3a1ca.firebasestorage.app',
    iosBundleId: 'com.example.appFinanzas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCdED9GvM7dpaSpIqGSTI3RdzZYSI48h0',
    appId: '1:780077026565:ios:259260e698d0b742f53b6c',
    messagingSenderId: '780077026565',
    projectId: 'appfinanzas-3a1ca',
    storageBucket: 'appfinanzas-3a1ca.firebasestorage.app',
    iosBundleId: 'com.example.appFinanzas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH8nE8TaB2c2FXirn-u8NRgiPr9YLaKVE',
    appId: '1:780077026565:web:2b3e85707c958e9cf53b6c',
    messagingSenderId: '780077026565',
    projectId: 'appfinanzas-3a1ca',
    authDomain: 'appfinanzas-3a1ca.firebaseapp.com',
    storageBucket: 'appfinanzas-3a1ca.firebasestorage.app',
    measurementId: 'G-NHBC3T5LZN',
  );
}
